# Generated by Django 5.2.7 on 2025-10-28 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWAB_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('tamaño', models.CharField(max_length=20)),
                ('estado_salud', models.TextField()),
                ('foto', models.ImageField(upload_to='mascotas/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_adopcion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SWAB_APP.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refugios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='SWAB_APP.refugio'),
        ),
    ]
