# Generated by Django 5.2.7 on 2025-10-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWAB_APP', '0002_mascota_adopcion_refugio_mascota_refugio'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='refugios/'),
        ),
    ]
