# Generated by Django 5.2.7 on 2025-10-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWAB_APP', '0003_refugio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('conejo', 'Conejo')], default='perro', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado_salud',
            field=models.CharField(blank=True, choices=[('sano', 'Sano'), ('enfermo', 'Enfermo'), ('recuperacion', 'Recuperacion')], default='sano', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='macho', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('grande', 'Grande'), ('mediano', 'Mediano'), ('chico', 'Chico')], default='mediano', max_length=20, null=True),
        ),
    ]
