# Generated by Django 5.2.7 on 2025-10-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWAB_APP', '0004_alter_mascota_especie_alter_mascota_estado_salud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('grande', 'Grande'), ('mediano', 'Mediano'), ('chico', 'Chico')], db_column='tamaño', default='mediano', max_length=20, null=True),
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='tamaño',
            new_name='tam',
        ),
    ]
